set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    ZIG_EXECUTABLE
    WIREHAIR_ZIG_TARGET
    WIREHAIR_TARGET_OS
    WIREHAIR_TARGET_ARCH
    WIREHAIR_OSX_SYSROOT
    WIREHAIR_OSX_DEPLOYMENT_TARGET
)

if(NOT DEFINED ZIG_EXECUTABLE OR ZIG_EXECUTABLE STREQUAL "")
    find_program(ZIG_EXECUTABLE NAMES zig REQUIRED)
endif()

if(NOT DEFINED WIREHAIR_ZIG_TARGET OR WIREHAIR_ZIG_TARGET STREQUAL "")
    message(FATAL_ERROR "WIREHAIR_ZIG_TARGET is required, for example x86_64-linux-gnu.2.17")
endif()

if(NOT DEFINED WIREHAIR_TARGET_OS OR WIREHAIR_TARGET_OS STREQUAL "")
    message(FATAL_ERROR "WIREHAIR_TARGET_OS must be one of: linux, windows, darwin")
endif()

if(NOT DEFINED WIREHAIR_TARGET_ARCH OR WIREHAIR_TARGET_ARCH STREQUAL "")
    message(FATAL_ERROR "WIREHAIR_TARGET_ARCH must be one of: x86_64, aarch64, arm64")
endif()

if(WIREHAIR_TARGET_OS STREQUAL "linux")
    set(CMAKE_SYSTEM_NAME Linux)
elseif(WIREHAIR_TARGET_OS STREQUAL "windows")
    set(CMAKE_SYSTEM_NAME Windows)
elseif(WIREHAIR_TARGET_OS STREQUAL "darwin")
    set(CMAKE_SYSTEM_NAME Darwin)
else()
    message(FATAL_ERROR "Unsupported WIREHAIR_TARGET_OS=${WIREHAIR_TARGET_OS}")
endif()

if(WIREHAIR_TARGET_ARCH STREQUAL "x86_64")
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
elseif(WIREHAIR_TARGET_ARCH STREQUAL "aarch64")
    set(CMAKE_SYSTEM_PROCESSOR aarch64)
elseif(WIREHAIR_TARGET_ARCH STREQUAL "arm64")
    set(CMAKE_SYSTEM_PROCESSOR arm64)
else()
    message(FATAL_ERROR "Unsupported WIREHAIR_TARGET_ARCH=${WIREHAIR_TARGET_ARCH}")
endif()

set(CMAKE_C_COMPILER "${ZIG_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_ARG1 cc CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "${ZIG_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_ARG1 c++ CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_TARGET "${WIREHAIR_ZIG_TARGET}" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET "${WIREHAIR_ZIG_TARGET}" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    if(NOT DEFINED WIREHAIR_OSX_SYSROOT OR WIREHAIR_OSX_SYSROOT STREQUAL "")
        message(FATAL_ERROR "WIREHAIR_OSX_SYSROOT must point at the macOS SDK when targeting Darwin")
    endif()

    set(CMAKE_OSX_SYSROOT "${WIREHAIR_OSX_SYSROOT}" CACHE PATH "" FORCE)

    set(_darwin_flags "-isysroot ${WIREHAIR_OSX_SYSROOT}")
    if(DEFINED WIREHAIR_OSX_DEPLOYMENT_TARGET AND NOT WIREHAIR_OSX_DEPLOYMENT_TARGET STREQUAL "")
        set(CMAKE_OSX_DEPLOYMENT_TARGET "${WIREHAIR_OSX_DEPLOYMENT_TARGET}" CACHE STRING "" FORCE)
        string(APPEND _darwin_flags " -mmacosx-version-min=${WIREHAIR_OSX_DEPLOYMENT_TARGET}")
    endif()

    set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} ${_darwin_flags}")
    set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} ${_darwin_flags}")
    set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_SHARED_LINKER_FLAGS_INIT} ${_darwin_flags}")
endif()
